### ISSUE TITLE
Interest in Transferring Project to Vox Pupuli?

### ISSUE THREAD

**Issue by yachub** [voxpupuli/puppet-lint-strict_indent-check#22]
Hi @relud 👋 Would you have any interest in transferring the ownership of this project and the associated [puppet-lint-strict_indent-check](https://rubygems.org/gems/puppet-lint-strict_indent-check) ruby gem to Vox Pupuli? That would enable more maintainers to review open issues and pull requests. Vox Pupuli is a community of module developers, they maintain ~140 modules and ~38 gems (the website is https://voxpupuli.org/). I believe that after the transfer you would not loose commit access to the repo.

I'm particularly interested in some community help with #19 and #21.

/cc @genebean

**Comment by genebean** [comment]
I love this plugin and would love to see it actively maintained. IMO, Vox Pupuli can facilitate that while still letting you keep all the access you want.

**Comment by relud** [comment]
i would love to

**Comment by genebean** [comment]
Awesome @relud! Are you on the puppet community slack? If so, what's your username there?

**Comment by relud** [comment]
I wasn't, but I am now, username is relud

**Comment by alexjfisher** [comment]
@relud I've sent you an invite to the voxpupuli github org.  After you accept, you should be able to transfer this repository.

**Comment by alexjfisher** [comment]
Repo has been transferred.  Thanks @relud !

I've opened https://github.com/voxpupuli/puppet-lint_modulesync_configs/pull/24
